version: "3"
services:
  client:
    depends_on:
      - server
      - python-api
    image: client:gcloud
    command: serve -n -s build -l 3000
    ports:
      - 8080:80
    volumes:
      - estore:/client
  server:
    image: server:prod
    command: npm run gcloud
    ports:
      - 5000:5000
    volumes:
      - estore:/server
  python-api:
    image: api:glcoud
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - estore:/api/python-api
volumes:
  estore: